apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsgzs1435-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsgzs1435-tenant-component
    app.kubernetes.io/part-of: loadsgzs1435-tenant-app
  name: loadsgzs1435-tenant-component
  namespace: loadsgzs1435-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsgzs1435-tenant-component
    weight: null
status: {}
